---
- name: Clause when
  hosts: debian,centos
    
  tasks:
    - name: Affichage du hostname si distribution Debian
      ansible.builtin.debug:
        msg: "Hostname: {{ ansible_hostname }}"
      when:
        - ansible_distribution == 'Debian'
        - ansible_distribution_version|int >= 11
