---
- name: Clause register
  hosts: debiancli

  tasks:
    - name: Tâche témoin
      ansible.builtin.shell:
        cmd: "grep {{ str }} /etc/psswd"
      register: result
      failed_when: result.rc > 1
      changed_when: false

    - name: Affichage de la variable result
      ansible.builtin.debug:
        msg: "Code retour: {{ result.rc }}"
