---
- name: Installation d'un serveur redis
  hosts: debian,centos
  become: true

  tasks:
    - name: Installation du paquet epel-release
      ansible.builtin.package:
        name: epel-release
        update_cache: true
      when: ansible_distribution == 'CentOS'

    - name: Installation du paquet du serveur Redis
      ansible.builtin.package:
        name: "{{ redis_package_name }}"
        update_cache: true

    - name: Configuration du service redis
      ansible.builtin.systemd:
        name: "{{ redis_service_name }}"
        state: started
        enabled: true

