---
- name: Clause when
  hosts: debian,centos

  tasks:
    - name: Clause block when
      when:
        - ansible_distribution == 'Debian'
      block:
        - name: Affichage du hostname si distribution Debian
          ansible.builtin.debug:
            msg: "Hostname: {{ ansible_hostname }}"

        - name: Affichage de l'architecture si distribution Debian
          ansible.builtin.debug:
            msg: "Arch: {{ ansible_architecture }}"
