---
- name: Reconfiguration du service redis
  hosts: debian
  become: true

  tasks:
    - name: Modificaton du fichier de configuration
      ansible.builtin.lineinfile:
        dest: "{{ redis_conf_filename }}"
        backup: true
        regex: ^bind
        line: "bind {{ ansible_host }}" 
      notify:
        - restart_redis

    - meta: flush_handlers

    - name: Tâche bidon
      ansible.builtin.debug:
        msg: "Fin du traitement"

  handlers:
    - name: Redémarrage du service redis
      ansible.builtin.systemd:
        name: "{{ redis_service_name }}"
        state: restarted
      listen:
        - restart_redis
