---
- name: Mise en place d'une solution LEMP
  hosts: www,php
  become: true

  roles:
    - role: nginx
      nginx_php_enabled: true
      when: inventory_hostname in groups.www

  post_tasks:
    - name: Copie du site
      ansible.builtin.copy:
        src: site/
        dest: "{{ nginx_document_root }}"


